-- CRIAÇÃO DO BANCO DE DADOS E TABELAS

CREATE DATABASE IF NOT EXISTS `bd_primesolutions` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `bd_primesolutions`;

CREATE TABLE CLIENTE 
(
    ID INT(3) UNSIGNED ZEROFILL AUTO_INCREMENT PRIMARY KEY,
    CPF VARCHAR(14) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    CELULAR VARCHAR(15) NOT NULL,
    DATA_C DATE NOT NULL
);

CREATE TABLE SERVICO
(
    ORDEM_SERVICO INT(5) UNSIGNED ZEROFILL PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT(3) UNSIGNED ZEROFILL NOT NULL,
    PLACA_CARRO VARCHAR(8) NOT NULL,
    MODELO_CARRO VARCHAR(40) NOT NULL,
    ANO VARCHAR(4),
    DATA_S DATE,
    VALOR_SERV DECIMAL(10,2),
    FORMA_PGT VARCHAR(15),
    GARANTIA VARCHAR(10),
    RESPONSAVEL VARCHAR(20),
    SERVICO_REALIZADO VARCHAR(255),
    STATUS ENUM('andamento', 'finalizado') NOT NULL DEFAULT 'andamento',
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID)
);

CREATE TABLE CADASTRO
(
    ID INT(11) NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    REPETICAO_SENHA VARCHAR(255),
    STATUS ENUM('aprovado', 'pendente', 'rejeitado') NOT NULL DEFAULT 'pendente',
    verification_code VARCHAR(32) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY unique_email (email),
    UNIQUE KEY unique_cpf (cpf)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- DADOS ADMIN
SET @verification_code = SHA1(CONCAT(NOW(), RAND()));

INSERT INTO CADASTRO (NOME, CPF, EMAIL, SENHA, REPETICAO_SENHA, STATUS, verification_code) 
VALUES 
('Admin TecnoAr', '00000000000', 'admintecnoar@admin.tecno', '$2y$10$1W7eV8MMZiQd.tNkV0xO2OvGANMAoDorqZpBgp9qG7KRSBPDVzqAu', '$2y$10$1W7eV8MMZiQd.tNkV0xO2OvGANMAoDorqZpBgp9qG7KRSBPDVzqAu', 'aprovado', @verification_code);

